### ISSUE TITLE
Safe name generation

### ISSUE THREAD

**Issue by sdkrystian** [cppalliance/mrdocs#166]
Unique, case insensitive, URL safe names need to be generated for each entity. For overloaded functions, each overload must be assigned a distinct name.

**Comment by klemens-morgenstern** [comment]
can't this just be the mangled name?

**Comment by vinniefalco** [comment]
> can't this just be the mangled name?

No, because those are enormous and they are case-insensitive. I tried it.

**Comment by sdkrystian** [comment]
This feature was implemented last year.
