### ISSUE TITLE
Distinguish unary versus binary operator+/-

### ISSUE THREAD

**Issue by vinniefalco** [cppalliance/mrdocs#186]
The return value of `getOverloadedOperator()` does not distinguish between the unary and binary forms of the following operators:
- `*`
- `&`
- `+`
- `-`

A full list of operators can be found at  https://github.com/llvm/llvm-project/blob/27c1051f730266d9fca275eb6c0b25c4440aec8b/clang/include/clang/Basic/OperatorKinds.def

**Comment by vinniefalco** [comment]
The list is

`+` `-` `*` `&` `++` `--`

**Comment by sdkrystian** [comment]
Whether an operator is unary or binary is dependent upon the parameters of the operator function.
