### ISSUE TITLE
cmake fails to find the dependency for 'fmt'

### ISSUE THREAD

**Issue by VWY-github** [cppalliance/mrdocs#271]
What is this missing 'fmt' dependency? What needs installing?

On Ubuntu 22.04 cmake fails with the following error:
`-- Looking for os_signpost_interval_begin - not found
CMake Error at CMakeLists.txt:117 (find_package):
  Could not find a package configuration file provided by "fmt" with any of
  the following names:

    fmtConfig.cmake
    fmt-config.cmake

  Add the installation prefix of "fmt" to CMAKE_PREFIX_PATH or set "fmt_DIR"
  to a directory containing one of the above files.  If "fmt" provides a
  separate development package or SDK, be sure it has been installed.

-- Configuring incomplete, errors occurred!
`

**Comment by alandefreitas** [comment]
If you just want need to have access to the binary, you can get it from the releases https://github.com/cppalliance/mrdox/releases
The project API is still unstable and the binaries are a little out of date, although we are about to update the master release soon.

If you really need it from source, then you can usually use vcpkg to have all the dependencies available and follow the external individual instructions for each of the dependencies.
In this recent PR https://github.com/cppalliance/mrdox/pull/273, I updated what these dependencies are and how to install each of them. It also downloads any missing dependencies in case they are not found.

**Comment by VWY-github** [comment]
Why dont you just use std::format in C++20 ?

**Comment by alandefreitas** [comment]
`fmt::format` is transitory because not all compilers implement std::format properly yet. Also, the project already has many other more serious dependencies. `fmt` shouldn't really be an additional problem at this point.

**Comment by VWY-github** [comment]
Could you at least provide the option to use std::format caveat emptor?

**Comment by alandefreitas** [comment]
> Could you at least provide the option to use std::format caveat emptor?

It's not impossible but it doesn't fix any problems. If you can't integrate libfmt, you won't be able to integrate LLVM+Clang, duktape, and all other dependencies. libfmt is really a small detail here.
