### ISSUE TITLE
Handlebars: options is dom::Object

### ISSUE THREAD

**Issue by vinniefalco** [cppalliance/mrdocs#391]
The Handlebars integration host needs the capability for defining integration-specific options which are stored and exposed through the Handlebars interface. Therefore the native form of `HandlebarsOptions` should be `dom::Object`. I don't think there is much point to providing a corresponding C++ `struct`, given that the host will almost always need to pass this object to the chosen scripting engine (or engines).

**Comment by vinniefalco** [comment]
I don't think that's what its for, because I'm thinking about settings that are accessed from the scripting language not the template. For example, these settings:

* `allowProtoMethodsByDefault `
* `allowedProtoMethods`
* `allowedProtoProperties`

described here:

https://handlebarsjs.com/api-reference/runtime-options.html#options-to-control-prototype-access

are strictly related to a JavaScript integration. The template doesn't care about these, but the scripting host does. Adding them to the `HandlebarsOptions` struct doesn't really make sense. If we want to design this library with scripting engines in mind then we want to make this use case simple:

```javascript
const template = handlebars.compile("{{aString.trim}}");
const result = template(
  { aString: "  abc  " },
  {
    allowedProtoMethods: {
      trim: true
    }
  }
);
```

**Comment by vinniefalco** [comment]
That's a lot of try-hard dude just fix the issue and stop writing novels

**Comment by vinniefalco** [comment]
That's using quite a few words just to say "I am prematurely optimizing the `HandlebarsOptions` struct." 

> the best place for these options depends on how the wrappers are accessing them. For instance, if we are wrapping the complete hbs.render function so that it can be called directly from JS, then the wrapped function should take options parameters with two logical sets of keys to be used when calling the underlying C++ function: the keys that will go into the C++ engine as options it understands and the keys that determine how the JS script will wrap the JS context into a dom::Value: with or without prototype access. 

The path of least resistance is just to put those engine-specific keys into `dom::Object` and call it a day. I sense a pattern of engaging in heroics for questionable gains.

**Comment by alandefreitas** [comment]
That's been implemented.
