### ISSUE TITLE
MrDox Fails to Generate Documents if Output Directory Doesn't Exist

### ISSUE THREAD

**Issue by fpelliccioni** [cppalliance/mrdocs#455]
## Description:

When using the `--output=<DIR>` option with MrDox, the specified `<DIR>` directory must pre-exist; otherwise, MrDox doesn't generate any documents nor reports errors or warnings to the user.

## Steps to Reproduce:

Run MrDox with the `--output=<DIR>` option where `<DIR>` is a directory that does not exist.
Observe that MrDox does not produce documents and does not alert the user that `<DIR>` needs to pre-exist.

## Expected Result:

MrDox should either create the `<DIR>` directory if it doesn't exist, or
MrDox should inform the user with an error or warning message indicating that the `<DIR>` directory does not exist.

## Actual Result:

MrDox does not generate documents and provides no feedback to the user regarding the output directory issue.

```
Mapping declarations
[1/2] "main.cpp"
[2/2] "MyClass.cpp"
No errors or warnings.

Collecting symbols
Reducing 6 declarations
Symbols collected: 6
Generating docs
```

**Comment by sdkrystian** [comment]
The output directory is created if it does not exist.
