### ISSUE TITLE
Need a button to navigate to the enclosing namespace

### ISSUE THREAD

**Issue by sdkrystian** [cppalliance/mrdocs#469]
It is often useful to navigate directly to the enclosing namespace of a symbol. Right now we link each component name individually in qualified names, but this could be replaced with a button to navigate to the enclosing namespace.

**Comment by alandefreitas** [comment]
@sdkrystian Can we close this issue? Does it still make any sense? I can't think of a place where a link to the parent symbol wouldn't look weird.
