### ISSUE TITLE
Rename `safenames` config option

### ISSUE THREAD

**Issue by sdkrystian** [cppalliance/mrdocs#472]
The concept of safenames is meaningless to the user. A name like `flat-files` might be better (or anything other than `safenames`)

**Comment by alandefreitas** [comment]
I think "flat files" would imply all files are in the same directory or something like that.

Maybe something to explore is "safe"/"legible"/etc names just being the default. Using hashes would be what the user needs to ask for explicitly. Like B2 has that option to use hashes for filenames. Or maybe the options just wouldn't exist and we would always generate "safe" names?

**Comment by sdkrystian** [comment]
@alandefreitas We ended up settling for "legible names".
