### ISSUE TITLE
MrDocs, MrDox! That crazy old fox, he rocks the dox!  (Pick one?)

### ISSUE THREAD

**Issue by sublimator** [cppalliance/mrdocs#568]
I see you actually have two domains?!

mrdocs.com ftw surely! and yet:

![image](https://github.com/cppalliance/mrdocs/assets/525211/4f399338-6a97-4c81-b863-ad9ee637312b)

?

**Comment by vinniefalco** [comment]
Yeah, "Dox" was a marketing fail. All occurrences of "dox" need to be changed to "docs."

**Comment by alandefreitas** [comment]
Problem solved...

![image](https://github.com/cppalliance/mrdocs/assets/5369819/d3f53a96-80b1-4c23-8914-fbe23c813f52)

**Comment by vinniefalco** [comment]
How is that problem solved? It literally says "MrDox" in the screenshot...

**Comment by sublimator** [comment]
README still uses Dox
