### ISSUE TITLE
GitHub Actions

### ISSUE THREAD

**Issue by Tsche** [cppalliance/mrdocs#60]
It would be very nice to have GitHub Actions within this repository, so common GitHub documentation workflows can be simplified.

I'd suggest 3 separate actions:
 - build documentation
 - publish to GH pages
 - publish to GH wiki 

Since MrDox outputs asciidoc pushing to the hidden wiki repositories (ie. `git@github.com:cppalliance/mrdox.wiki.git` for this repository once enabled) should yield usable results.

**Comment by alandefreitas** [comment]
This has been implemented as the demos on the mrdocs.com website. 5bd2cc49
