### ISSUE TITLE
Improve documentation for path behavior in MrDocs

### ISSUE THREAD

**Issue by fpelliccioni** [cppalliance/mrdocs#617]
Based on the discussion in [issue #529](https://github.com/cppalliance/mrdocs/issues/529) and Alan's comment [here](https://github.com/cppalliance/mrdocs/issues/529#issuecomment-2146269043), we need to improve the documentation to clarify that:

- Paths specified in the command line override the values in `mrdocs.yml`.
- All paths, whether in `mrdocs.yml` or the command line, are relative to the location of `mrdocs.yml`.
- The rationale is that `mrdocs.yml` is at a stable location in the project, and having paths relative to it avoids verbosity and inconsistency.

This will help users understand the expected behavior and avoid confusion.

**Comment by alandefreitas** [comment]
Fixed by https://github.com/cppalliance/mrdocs/pull/622
