### ISSUE TITLE
Folding overloads into one page

### ISSUE THREAD

**Issue by alandefreitas** [cppalliance/mrdocs#647]
Dmitry did some work on folding overloads together into one page with docca.

https://1024.jsondocs.prtest.cppalliance.org/libs/json/doc/html/json/ref/boost__json__parse.html

The algorithm for merging the @brief and @details is simple: it uses the first overload for the documentation. The only thing that's merged is the parameters tables.

The results are nice. It's almost like cppreference. The algorithm is surprisingly good enough: if the first overload has the fewest parameters, its brief, and details should be general enough for the overload page. In the case of Boost.JSON, the assumption is that its description is written as if for all overloads.

We cannot assume this in MrDocs because we still have a page for each overload. But we can still merge the overloads at the template level in MrDocs. Taking the first overload is a good starting point. If we want to make it complex, the one with the fewest parameters could become the main one, and then we would add "(x) details" for each overload where "details" is the diff of the other overload.

We must investigate and discuss the options for merging the documentation from different overloads.

**Comment by vinniefalco** [comment]
Mr. Docs must know the number of pages and what is on each page ahead of time (i.e. before rendering them). To implement this feature, it will be necessary to have a configuration setting to merge overloads into a single page. And the templates will need to be specialized for each mode.
