### ISSUE TITLE
Review LazyObjectImpl::obj()

### ISSUE THREAD

**Issue by alandefreitas** [cppalliance/mrdocs#696]
Most compilers don't implement `__cpp_lib_atomic_shared_ptr`, on which `LazyObjectImpl` depends:

https://github.com/cppalliance/mrdocs/blob/a962db0fc4a309afa11e956fbe9b9880e39c92f0/src/lib/Dom/Object.cpp#L216-L232

For this reason, the function above contains two implementations, depending on whether `__cpp_lib_atomic_shared_ptr` is supported.

Both implementations are problematic:

- The implementation is not thread-safe when `__cpp_lib_atomic_shared_ptr` is unsupported. The object would need to carry a pointer to mutex for that.
- The implementation when `__cpp_lib_atomic_shared_ptr` is supported is also unsafe because the load and exchange operations are independent. This means two concurrent threads will attempt to construct the object twice if they call the function before the object is constructed.

**Comment by vinniefalco** [comment]
sad
