### ISSUE TITLE
Provide Config Schema

### ISSUE THREAD

**Issue by Nerixyz** [cppalliance/mrdocs#700]
RedHat's [YAML language server](https://github.com/redhat-developer/yaml-language-server) provides the option to associate a file with some schema by adding a [special top level comment](https://github.com/redhat-developer/yaml-language-server?tab=readme-ov-file#using-inlined-schema) (or through the settings). It would be really helpful is MrDocs would provide a schema for the config. This makes editing a much nicer experience, in my opinion. [Mkdocs-material provides such a schema for example](https://squidfunk.github.io/mkdocs-material/creating-your-site/#configuration).

Given that MrDocs has the configuration in a [machine-readable format already](https://github.com/cppalliance/mrdocs/blob/5e0f628e5b1cdb06a3dd260e0e42069f12733353/src/lib/Lib/ConfigOptions.json), this seems easy to add. I modified `generate-config-info.py` a bit to generate a JSON (and thus YAML) schema:

<img height="400" src="https://github.com/user-attachments/assets/e931524d-ea74-4564-a4fe-bf8ef54c23ba">

If this something you'd like to add? If so, I'd open a PR.

**Comment by vinniefalco** [comment]
Very good idea! This would be nicer as a pull request though ;)
