### ISSUE TITLE
Descriptions with paragraphs, code, and other elements rendered incorrectly

### ISSUE THREAD

**Issue by anarthal** [cppalliance/mrdocs#765]
```cpp
/// This is another function.
void other_function();

/**
 * \brief A function
 * \details Relies on \ref other_function.
 *
 * Example:
 * \code
 *   my_function();
 * \endcode
 *
 * \par Exception safety
 * No-throw guarantee.
 */
void my_function();
```

Renders

![Image](https://github.com/user-attachments/assets/3b4c685c-e0bf-4932-92f3-e6f837c55c60)

**Comment by Nerixyz** [comment]
Which version of mrdocs are you using? This looks fine in the [current release](https://github.com/cppalliance/mrdocs/releases/tag/develop-release):

![Image](https://github.com/user-attachments/assets/92d0d2d0-856a-4e8f-a846-889fb17754f6)

**Comment by anarthal** [comment]
No, this image is not fine. The title should be Exception safety, which is missing, and not No-throw guarantee.
